# file is processed in order
# Fred & Wilma but not Bambam...
- sni match: '.*' # matches everything (all hostnames)
  o: '^Flintstone$'
  cn:
    allow:
      match:
      - 'Fred Flintstone'
      - 'Wilma Flintstone'
