# file is processed in order
# Ken & Marcy
revocation list:
hosts:
  - sni match: '.*' # matches everything
    o: '^Pratt$'
    cn:
      allow:
        match:
        - 'Ken Pratt'
        - 'Marcy Pratt'